### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by lilymtang** [MLH-Fellowship/clarify#31]
Running list of improvements:
- [x] Join code in upper right hand corner
- [x] Align question cards and question submission text box to be the same width.
- [x] Put questions in scrollable div
- [x] Center poll buttons
- [x] Make poll take up 2/3 of the poll + question container
- [x] Add more padding on left and right of site
- [x] Make logo clickable

**Comment by ZzRanger** [comment]
- I'll do join code, make logo clickable, and add background gradient
